### ISSUE TITLE
Windows-64 bit + macOS support

### ISSUE THREAD

**Issue by SolidSoft-Lda** [RayGyoe/ANEWinWebView#1]
Please, don't forget about Windows-64 bit support.

This support all Windows versions where AIR runs or only Windows 10 ?
There are any dependencies on Windows (must have .NET Framework version X installed, etc ...) ?
Do you have plans to include macOS support ?

**Comment by RayGyoe** [comment]
1.adapt to all windows versions.（time permitting, I will support 64x）
2.not suitable for other operating systems.

**Comment by SolidSoft-Lda** [comment]
64x is important.
Any modern OS use 64x.
32x is for retro-compatibility.

Hope you change your mind about macOS support :)
If you need, I can help you with tests.

**Comment by SolidSoft-Lda** [comment]
I found an alternative for macOS.
The only this that is missing is x64 on yours :)

**Comment by RayGyoe** [comment]
x64 is finish

**Comment by SolidSoft-Lda** [comment]
Thank you very much.
I will test ASAP.

**Comment by RayGyoe** [comment]
demo ：https://github.com/RayGyoe/ANEWinWebView/releases
